/** Field Desk utility layer: quiet, defensive file helpers for a local workspace. */
import type { DocumentCategory, FileCapabilities, LocalDocument } from "@/types/documents";
const CATEGORY_BY_EXTENSION: Record<string, DocumentCategory> = { pdf: "pdf", doc: "document", docx: "document", odt: "document", rtf: "document", txt: "document", md: "document", markdown: "document", html: "document", htm: "document", epub: "document", xls: "document", xlsx: "document", ods: "document", ppt: "document", pptx: "document", odp: "document", jpg: "image", jpeg: "image", png: "image", webp: "image", gif: "image", bmp: "image", tif: "image", tiff: "image", avif: "image", svg: "image", mp3: "media", wav: "media", m4a: "media", ogg: "media", mp4: "media", webm: "media", mov: "media", json: "data", xml: "data", yaml: "data", yml: "data", csv: "data", zip: "archive", rar: "archive", "7z": "archive", tar: "archive", gz: "archive" };
const TEXT_EXTENSIONS = new Set(["txt", "md", "markdown", "json", "xml", "yaml", "yml", "csv", "html", "htm", "rtf"]);
export function getExtension(filename: string) { const name = filename.trim(); const dot = name.lastIndexOf("."); return dot > 0 ? name.slice(dot + 1).toLowerCase() : ""; }
export function getCategory(filename: string): DocumentCategory { return CATEGORY_BY_EXTENSION[getExtension(filename)] ?? "other"; }
export function isTextDocument(document: Pick<LocalDocument, "extension" | "mimeType">) { return TEXT_EXTENSIONS.has(document.extension) || document.mimeType.startsWith("text/"); }
export function isImageDocument(document: Pick<LocalDocument, "category">) { return document.category === "image"; }
export function isMediaDocument(document: Pick<LocalDocument, "category">) { return document.category === "media"; }
export function sanitizeFilename(value: string) { const cleaned = value.replace(/[\\/:*?"<>|\u0000-\u001F]/g, " ").replace(/\s+/g, " ").replace(/^\.+|\.+$/g, "").trim(); return cleaned || "Untitled"; }
export function makeUniqueFilename(requestedName: string, existingNames: string[]) { const safeName = sanitizeFilename(requestedName); const lowerNames = new Set(existingNames.map((name) => name.toLocaleLowerCase())); if (!lowerNames.has(safeName.toLocaleLowerCase())) return safeName; const dot = safeName.lastIndexOf("."); const base = dot > 0 ? safeName.slice(0, dot) : safeName; const extension = dot > 0 ? safeName.slice(dot) : ""; let index = 2; let candidate = `${base} (${index})${extension}`; while (lowerNames.has(candidate.toLocaleLowerCase())) { index += 1; candidate = `${base} (${index})${extension}`; } return candidate; }
export function formatBytes(bytes: number) { if (bytes === 0) return "0 B"; const units = ["B", "KB", "MB", "GB"]; const exponent = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1); return `${(bytes / 1024 ** exponent).toFixed(exponent === 0 ? 0 : 1)} ${units[exponent]}`; }
export function formatDate(value: string, locale: string) { return new Intl.DateTimeFormat(locale, { day: "numeric", month: "short", year: "numeric" }).format(new Date(value)); }
export function datedPath(filename: string, date = new Date()) { const year = date.getFullYear(); const month = String(date.getMonth() + 1).padStart(2, "0"); return `${year}/${month}/${filename}`; }
export function timestampedFilename(label: string, extension: string, date = new Date()) { const day = [date.getFullYear(), String(date.getMonth() + 1).padStart(2, "0"), String(date.getDate()).padStart(2, "0")].join("-"); const time = [String(date.getHours()).padStart(2, "0"), String(date.getMinutes()).padStart(2, "0")].join(""); return `${day}_${time}_${label}.${extension.replace(/^\./, "")}`; }
export function documentCapabilities(document: Pick<LocalDocument, "category" | "extension" | "mimeType">): FileCapabilities { const text = isTextDocument(document); const preview = text || document.category === "pdf" || document.category === "image" || document.category === "media"; return { preview, edit: text ? "basic" : "none", extractText: text, convertTo: document.category === "image" ? ["PDF"] : [], print: document.category === "pdf" || text || document.category === "image", share: typeof navigator !== "undefined" && "share" in navigator }; }
export function iconLabel(document: Pick<LocalDocument, "category" | "extension">) { if (document.category === "pdf") return "PDF"; if (document.category === "image") return "IMG"; if (document.category === "media") return document.extension.toUpperCase(); if (document.category === "archive") return "ZIP"; if (document.category === "data") return "DATA"; return document.extension ? document.extension.toUpperCase().slice(0, 4) : "FILE"; }
